### PR TITLE
Add IMDB rating and cast of currently playing episode

### PR DESCRIPTION
**Pull request by agarwalrounak**
Partially solves #7 by fetching 2 out of the 3 information required.
### Changes
Fetches Cast and IMDB rating of currently playing episode on VLC.
### Screenshots
When playing `Doctor Who S05E12.mkv`
screenshot from 2018-12-15 16-35-54

When playing `Two and a half men S01E1.mkv`
screenshot from 2018-12-15 16-39-42

When playing `Bojack Horseman S3E07.mkv`
screenshot from 2018-12-15 16-41-19

### CODE REVIEW

**Comment by kaustubhhiware** [comment]
Impressive work :+1: 
Quotes if not fetched can be worked upon subsequently, don't worry about that.

Could you tell me what was the file title playing in vlc when you ran the script? 
That is going to be one issue, extracting the name from a poorly named file, which somehow contains all the relevant information.

**Comment by agarwalrounak** [comment]
You mean the file name, right?

**Comment by kaustubhhiware** [comment]
Yes, from the looks of it you're assuming the names are well formatted. Well you and I both know that's hardly the case. The code should be robust enough to handle names like

* Doctor.Who.S05e12.extraneoustext.mkv
* Attack On Titan - S03E01 - Smoke Signal (720p) (x265) (E-Subs) [Baba_Bhayanak].mkv
* Bojack Horseman - S01E01 [WEBRip 720p] [Daiki_Aomine].mkv
* Brooklyn.Nine-Nine.S01E01.1080p.WEB-DL.DD5.1.H.264-NTb.mkv

to name a few. If we cover this, the PR would be perfect. 

One approach could be using regex (regular expressions) to extract S<num><num>E<num><num> from the text, and remove all texts in different brackets, to obtain the show title. Assume for now, the show name starts from the beginning. Another test case would be providing "Doctor.Who" instead of "Doctor Who"

**Comment by kaustubhhiware** [comment]
@agarwalrounak any updates?

If you think handling the name edgecases would be hectic, we can create a new issue for that and merge this work as it is currently.

**Comment by agarwalrounak** [comment]
Yes, please merge this work as it is currently. 
At present, I don't have access to my laptop. I will able to work on this project from 19th onwards again. When you create a new issue for handling the name edgecases, please assign it to me. I would love to work on that. 
Thanks a lot! :smiley:

**Pull request merged**
