### PR TITLE
Added switch and tables

### PR DESCRIPTION
**Pull request by Harsh5557**
Will add spinning loader soon.

### CODE REVIEW

**Comment by kaustubhhiware** [comment]
Could you add a screenshot for this change?
Would be easier to review.

**Comment by Harsh5557** [comment]
Added the screen shots.

**Comment by kaustubhhiware** [comment]
The landing page looks good.

However for the tvseries page, could you have a table where rows are seasons and columns are episode numbers. A 2-d matrix M where M[x][y] is imdb rating of SxEy.

Such a system would be much more convenient.

**Comment by kaustubhhiware** [comment]
LGTM :+1: 

Merging this in. Great work :smile:

**Comment by Harsh5557** [comment]
Thanks👍

**Pull request merged**
